### ISSUE TITLE
Handle channel errors

### ISSUE THREAD

**Issue by likethemammal** [akenn/helpybot#4]
When a slack channel is private **OR** the bot hasn't been invited yet, `getChannelByName` returns undefined. I can understand that result if the channel didn't exist, but either way a helpful error message would be.. helpful.

Maybe something letting the dev know the channel might be private.

**Comment by L1fescape** [comment]
:+1: I'll start working on this tonight or tomorrow

**Comment by akenn** [comment]
Fixed with v0.1.2

**Comment by L1fescape** [comment]
Fixed with fff3a00c5ae0125c97527b87497bee535df3e840
